import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language ts ./types`.

export type Projects = Models.Row & {
    project_title: string;
    project_meta_description: string;
    project_link: string;
    project_skills: string[] | null;
    img_url: string | null;
    isPublished: boolean;
}

export type AboutSection = Models.Row & {
    about_description: string;
}

export type Socials = Models.Row & {
    linkedin_url: string;
    github_url: string;
}

export type HeroImageUrl = Models.Row & {
    hero_image_url: string;
}
